### ISSUE TITLE
[Feature request] Independent label color

### ISSUE THREAD

**Issue by Mistmage** [gapmiss/inline-callouts#3]
Right now, if background transparency is disabled, text becomes invisible.

```
.inline-callout-label, .inline-callout-icon {
  color: white !important;
}

```

fixes that, but i would be nice to have independent color variable set via additional |
Inside of the every callout.

**Comment by Mistmage** [comment]
Right now you need sacrifice some icons,  just to have text as a variable


```


.inline-callout[data-inline-callout="ambulance"] .inline-callout-label {
  color: #a570f5;
}

.inline-callout[data-inline-callout="accessibility"] .inline-callout-label {
  color: #FFD700;
}

.inline-callout[data-inline-callout="banana"] .inline-callout-label {
  color: #C0C0C0;
}

.inline-callout[data-inline-callout="baby"] .inline-callout-label {
  color: #CD7F32;
}




/* Hide the icon for those same data-inline-callout values */
.inline-callout[data-inline-callout="ambulance"] > .inline-callout-icon,
.inline-callout[data-inline-callout="accessibility"] > .inline-callout-icon,
.inline-callout[data-inline-callout="banana"] > .inline-callout-icon,
.inline-callout[data-inline-callout="baby"] > .inline-callout-icon {
  display: none !important;
}

```

**Comment by gapmiss** [comment]
This can be achieved with CSS. When background transparency is low/disabled, override the text color:

```css
/* Global override */
.inline-callout-label, .inline-callout-icon {
    color: white !important;
}
/* Or target specific icons */
[data-inline-callout="alert"] .inline-callout-label {
    color: var(--text-on-accent) !important;
}
```

Since CSS provides full flexibility here (global, per-icon, or per-theme), I'm keeping the syntax simple and not adding a 4th parameter. Let me know if the CSS approach doesn't work for your use case.
